[16.0][ADD] base_wamas_ubl: Add new module to convert WAMAS files to UBL files and vice versa
tuantrantg/edi pull request #7
Opened 2023-11-29 10:11 UTC by tuantrantg

2023-11-29 10:21 UTC, nilshamerlinck requested changes

2023-11-29 10:21 UTC, nilshamerlinck commented on base_wamas_ubl/lib/wamas/ubl_template/picking.xml
> +			<cbc:LineID></cbc:LineID>
we can probably use `<t t-raw="record_index"/>` here as well to get a valid value

2023-11-29 10:21 UTC, nilshamerlinck commented on base_wamas_ubl/lib/wamas/ubl2wamas.py
> +MAPPING_UBL_TO_WAMAS = {
hmm can't build it from the existing mapping?

2023-11-29 10:21 UTC, nilshamerlinck commented on base_wamas_ubl/lib/wamas/ubl2wamas.py
> +def _set_string(val, length, dp):
could you add a `test_ubl2wamas.py` that tests for expected values of these helpers?

2023-11-30 04:22 UTC, tuantrantg commented
hi @nilshamerlinck please review your requests again, I've updated the PR

2023-12-25 08:22 UTC, closed without merging